import type { NextPage } from 'next';
import Head              from 'next/head';
import Container         from '../src/components/Container';

const Home: NextPage = () => {
  return (
    <div className="w-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Container />
    </div>
  )
}

export default Home
